### ISSUE TITLE
glob() failed with return value 3

### ISSUE THREAD

**Issue by Gatix1** [RauliL/gtk-pass#1]
how can i fix this error: glob() failed with return value 3?
It appears after launching the program, and there is just an empty search bar, which does not actually work

**Comment by RauliL** [comment]
Hello there. At least on my Linux machine return value 3 from `glob()` function is `GLOB_NOMATCH` error, meaning that no entries that match `*.gpg` are found from your password store. This could mean couple of things.

1. Your password store is located somewhere else than in `~/.password-store`. In this case you should set environment variable `PASSWORD_STORE_DIR` to point to the location of your password store.
2. Your password entries use some other file extension than `.gpg`. (I highly doubt this is the case.)
3. The glob pattern used by this application cannot find the entries as they are not stored into subdirectories.

I will look at the glob pattern issue, as I have a hunch that globbing `**/*.gpg` does not detect entries that are not stored under a subdirectory.

**Comment by RauliL** [comment]
It turned out to be a glob pattern issue. This has been fixed in version 1.4.
